// flow-typed signature: c89d6ba80d604d41429c748a9f12e318
// flow-typed version: <<STUB>>/eslint-plugin-jsdoc_v^18.1.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsdoc/dist/bin/generateReadme' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/eslint/getJSDocComment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/exportParser' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/iterateJsdoc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/jsdocUtils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkAccess' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkAlignment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkExamples' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkIndentation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkParamNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkSyntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkTagNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/checkValues' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/emptyTags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/implementsOnClasses' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/matchDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/newlineAfterDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/noTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/noUndefinedTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireDescriptionCompleteSentence' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireExample' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireHyphenBeforeParamDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireJsdoc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParam' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParamDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParamName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireParamType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireReturns' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsCheck' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/rules/validTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/tagNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/warnRemovedSettings' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/dist/WarnSettings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsdoc/dist/bin/generateReadme.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/bin/generateReadme'>;
}
declare module 'eslint-plugin-jsdoc/dist/eslint/getJSDocComment.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/eslint/getJSDocComment'>;
}
declare module 'eslint-plugin-jsdoc/dist/exportParser.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/exportParser'>;
}
declare module 'eslint-plugin-jsdoc/dist/index' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist'>;
}
declare module 'eslint-plugin-jsdoc/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist'>;
}
declare module 'eslint-plugin-jsdoc/dist/iterateJsdoc.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/iterateJsdoc'>;
}
declare module 'eslint-plugin-jsdoc/dist/jsdocUtils.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/jsdocUtils'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkAccess.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkAccess'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkAlignment.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkAlignment'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkExamples.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkExamples'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkIndentation.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkIndentation'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkParamNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkParamNames'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkSyntax.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkSyntax'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkTagNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkTagNames'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/checkValues.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/checkValues'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/emptyTags.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/emptyTags'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/implementsOnClasses.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/implementsOnClasses'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/matchDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/matchDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/newlineAfterDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/newlineAfterDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/noTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/noTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/noUndefinedTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/noUndefinedTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireDescriptionCompleteSentence.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireDescriptionCompleteSentence'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireExample.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireExample'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireHyphenBeforeParamDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireHyphenBeforeParamDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireJsdoc.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireJsdoc'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParam.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParam'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParamDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParamDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParamName.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParamName'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireParamType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireParamType'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireReturns.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireReturns'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsCheck.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireReturnsCheck'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireReturnsDescription'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/requireReturnsType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/requireReturnsType'>;
}
declare module 'eslint-plugin-jsdoc/dist/rules/validTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/rules/validTypes'>;
}
declare module 'eslint-plugin-jsdoc/dist/tagNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/tagNames'>;
}
declare module 'eslint-plugin-jsdoc/dist/warnRemovedSettings.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/warnRemovedSettings'>;
}
declare module 'eslint-plugin-jsdoc/dist/WarnSettings.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/dist/WarnSettings'>;
}
