// flow-typed signature: f765193a90f7a17ab008339f39243ace
// flow-typed version: <<STUB>>/js-logger_v^1.6.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-logger/src/logger' {
  declare module.exports: any;
}

declare module 'js-logger/src/logger.min' {
  declare module.exports: any;
}

declare module 'js-logger/test-src/loggertests' {
  declare module.exports: any;
}

declare module 'js-logger/test-src/vendor/qunit-1.18.0' {
  declare module.exports: any;
}

declare module 'js-logger/test-src/vendor/sinon-1.14.1' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-logger/src/logger.js' {
  declare module.exports: $Exports<'js-logger/src/logger'>;
}
declare module 'js-logger/src/logger.min.js' {
  declare module.exports: $Exports<'js-logger/src/logger.min'>;
}
declare module 'js-logger/test-src/loggertests.js' {
  declare module.exports: $Exports<'js-logger/test-src/loggertests'>;
}
declare module 'js-logger/test-src/vendor/qunit-1.18.0.js' {
  declare module.exports: $Exports<'js-logger/test-src/vendor/qunit-1.18.0'>;
}
declare module 'js-logger/test-src/vendor/sinon-1.14.1.js' {
  declare module.exports: $Exports<'js-logger/test-src/vendor/sinon-1.14.1'>;
}
